INSERT INTO student (name, birthday, groupnumber) VALUES ('John', '2002-12-04', 1);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Chris', '2001-12-04', 1);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Carl', '2000-12-04', 1);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Oliver', '1996-12-04', 2);
INSERT INTO student (name, birthday, groupnumber) VALUES ('James', '1999-12-04', 2);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Lucas', '2000-09-04', 2);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Henry', '2000-01-04', 2);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Jacob', '2000-12-04', 3);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Logan', '2000-10-04', 3);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Alex', '2000-11-04', 4);
INSERT INTO student (name, birthday, groupnumber) VALUES ('Sam', '2000-12-04', 5);
INSERT INTO subject (name, description, grade) VALUES ('Art', 'art', 1);
INSERT INTO subject (name, description, grade) VALUES ('Music', 'music', 1);
INSERT INTO subject (name, description, grade) VALUES ('Geography', 'geo', 2);
INSERT INTO subject (name, description, grade) VALUES ('History', 'history', 2);
INSERT INTO subject (name, description, grade) VALUES ('PE', 'pe', 3);
INSERT INTO subject (name, description, grade) VALUES ('Math', 'math', 3);
INSERT INTO subject (name, description, grade) VALUES ('Science', 'science', 4);
INSERT INTO subject (name, description, grade) VALUES ('IT', 'it', 4);
INSERT INTO subject (name, description, grade) VALUES ('Photography', 'photo', 5);
INSERT INTO subject (name, description, grade) VALUES ('Programming', 'progr', 5);
insert into paymenttype (name) values ( 'DAILY');
insert into paymenttype (name) values ('WEEKLY');
insert into paymenttype (name) values ( 'MONTHLY');
INSERT INTO payment (type_id, amount, payment_date, student_id) VALUES (2, 101.5, '2020-12-01', 1);
INSERT INTO payment (type_id, amount, payment_date, student_id) VALUES (3, 215.4, '2019-04-15', 4);
INSERT INTO payment (type_id, amount, payment_date, student_id) VALUES (2, 129.7, '2018-05-17', 7);
INSERT INTO payment (type_id, amount, payment_date, student_id) VALUES (1, 215.4, '2019-04-15', 5);
INSERT INTO payment (type_id, amount, payment_date, student_id) VALUES (1, 215.4, '2019-04-15', 8);
INSERT INTO payment (type_id, amount, payment_date, student_id) VALUES (3, 215.4, '2019-04-15', 3);
INSERT INTO mark (student_id, subject_id, mark) VALUES (2, 1, 8);
INSERT INTO mark (student_id, subject_id, mark) VALUES (4, 4, 5);
INSERT INTO mark (student_id, subject_id, mark) VALUES (5, 3, 9);
INSERT INTO mark (student_id, subject_id, mark) VALUES (8, 6, 4);
INSERT INTO mark (student_id, subject_id, mark) VALUES (9, 5, 9);
INSERT INTO mark (student_id, subject_id, mark) VALUES (1, 5, 7);
