ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE mark add check (mark >= 1 AND mark <= 10);
ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject add check (GRADE >= 1 AND GRADE <= 5);
ALTER TABLE paymenttype add UNIQUE(paymenttype.name);
ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment ALTER COLUMN amount NUMERIC NOT NULL;
ALTER TABLE payment ALTER COLUMN payment_date TIMESTAMP NOT NULL;