CREATE TABLE Student (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30), birthday DATE, group_num INT);
CREATE TABLE Subject
(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30),
description VARCHAR(50),
grade INT);
CREATE TABLE PaymentType
(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30));
CREATE TABLE Payment
(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
type_id BIGINT NOT NULL,
amount DECIMAL,
student_id BIGINT NOT NULL,
payment_date DATETIME,
FOREIGN KEY (type_id)  REFERENCES PaymentType (id),
FOREIGN KEY (student_id)  REFERENCES Student (id));
CREATE TABLE Mark
(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
student_id BIGINT NOT NULL,
subject_id BIGINT NOT NULL,
mark INT,
FOREIGN KEY (student_id)  REFERENCES Student (id),
FOREIGN KEY (subject_id)  REFERENCES Subject (id));

